// server/utils/excelGenerator.js

const ExcelJS = require('exceljs');

/**
 * Generates an Excel report for a whole exam showing all student marks.
 *
 * @param {Object} exam - Mongoose Exam document
 * @param {Array}  submissions - Array of Submission documents sorted by rollNumber
 * @returns {Promise<Buffer>} - Excel file as a Node.js Buffer
 */
const generateExcelReport = async (exam, submissions) => {
  const workbook = new ExcelJS.Workbook();

  // Workbook metadata
  workbook.creator = 'EvalAI';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet('Results');

  // ── Column definitions ─────────────────────────────────────────────────
  // width is in character units — we set minimums and let content stretch
  sheet.columns = [
    { header: 'Roll Number',    key: 'rollNumber',        width: 20 },
    { header: 'Marks Awarded',  key: 'totalMarksAwarded', width: 16 },
    { header: 'Total Marks',    key: 'totalMarks',        width: 14 },
    { header: 'Percentage',     key: 'percentage',        width: 14 },
    { header: 'Status',         key: 'status',            width: 14 },
    { header: 'Flagged',        key: 'isFlagged',         width: 10 },
  ];

  // ── Row 1: Title row merged across all 6 columns ───────────────────────
  // We insert a title row before the auto-generated header row
  sheet.spliceRows(1, 0, []); // Insert blank row at position 1
  sheet.getRow(1).getCell(1).value = `${exam.title} — ${exam.subject}`;
  sheet.mergeCells('A1:F1');

  const titleCell = sheet.getRow(1).getCell(1);
  titleCell.font = { bold: true, size: 14, color: { argb: 'FF1E3A5F' } };
  titleCell.alignment = { horizontal: 'center', vertical: 'middle' };
  titleCell.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFE8F0FE' },
  };
  sheet.getRow(1).height = 30;

  // ── Row 2: Empty spacing row ───────────────────────────────────────────
  sheet.spliceRows(2, 0, []);
  sheet.getRow(2).height = 8;

  // ── Row 3: Header row (auto-generated by exceljs from column definitions)
  // The header row is now at position 3 because we inserted 2 rows above
  const headerRow = sheet.getRow(3);
  headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
  headerRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF1D4ED8' }, // Blue background
  };
  headerRow.alignment = { horizontal: 'center', vertical: 'middle' };
  headerRow.height = 22;

  // Apply border to all header cells
  headerRow.eachCell((cell) => {
    cell.border = {
      top:    { style: 'thin', color: { argb: 'FF1E40AF' } },
      bottom: { style: 'thin', color: { argb: 'FF1E40AF' } },
      left:   { style: 'thin', color: { argb: 'FF1E40AF' } },
      right:  { style: 'thin', color: { argb: 'FF1E40AF' } },
    };
  });

  // ── Data rows ──────────────────────────────────────────────────────────
  // Sort submissions by rollNumber ascending — defensive sort in case they
  // arrive in a different order
  const sorted = [...submissions].sort((a, b) =>
    a.rollNumber.localeCompare(b.rollNumber)
  );

  sorted.forEach((submission, index) => {
    const rowNumber = index + 4; // Data starts at row 4 (1=title, 2=blank, 3=header)

    const row = sheet.addRow({
      rollNumber:        submission.rollNumber,
      totalMarksAwarded: submission.totalMarksAwarded,
      totalMarks:        submission.totalMarks,
      percentage:        submission.percentage,
      status:            submission.status,
      isFlagged:         submission.isFlagged ? 'Yes' : 'No',
    });

    // Alternating row background colors for readability
    const bgColor = index % 2 === 0 ? 'FFFAFAFA' : 'FFF0F4FF';
    row.eachCell((cell) => {
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: bgColor },
      };
      cell.alignment = { horizontal: 'center', vertical: 'middle' };
      cell.border = {
        bottom: { style: 'hair', color: { argb: 'FFE5E7EB' } },
      };
    });

    // Color the status cell based on value
    const statusCell = row.getCell('status');
    if (submission.status === 'completed') {
      statusCell.font = { color: { argb: 'FF16A34A' }, bold: true };
    } else if (submission.status === 'failed') {
      statusCell.font = { color: { argb: 'FFDC2626' }, bold: true };
    } else {
      statusCell.font = { color: { argb: 'FF6B7280' } };
    }

    // Color flagged cell red if flagged
    const flaggedCell = row.getCell('isFlagged');
    if (submission.isFlagged) {
      flaggedCell.font = { color: { argb: 'FFDC2626' }, bold: true };
    }

    // Format percentage cell with % symbol
    const percentCell = row.getCell('percentage');
    percentCell.numFmt = '0.00"%"';

    row.height = 18;
  });

  // ── Auto-fit column widths based on content ────────────────────────────
  sheet.columns.forEach((column) => {
    let maxLength = column.header ? column.header.length : 10;
    column.eachCell({ includeEmpty: false }, (cell) => {
      const cellLength = cell.value ? String(cell.value).length : 0;
      if (cellLength > maxLength) maxLength = cellLength;
    });
    column.width = Math.min(maxLength + 4, 40); // cap at 40 chars wide
  });

  // ── Summary row at the bottom ──────────────────────────────────────────
  const completedCount = submissions.filter((s) => s.status === 'completed').length;
  const avgPercentage =
    completedCount > 0
      ? (
          submissions
            .filter((s) => s.status === 'completed')
            .reduce((sum, s) => sum + s.percentage, 0) / completedCount
        ).toFixed(2)
      : 0;

  sheet.addRow([]); // blank spacer
  const summaryRow = sheet.addRow({
    rollNumber: 'SUMMARY',
    totalMarksAwarded: '',
    totalMarks: '',
    percentage: Number(avgPercentage),
    status: `${completedCount} completed`,
    isFlagged: '',
  });

  summaryRow.font = { bold: true, color: { argb: 'FF1E3A5F' } };
  summaryRow.getCell('percentage').numFmt = '0.00"%"';
  summaryRow.eachCell((cell) => {
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE8F0FE' },
    };
  });

  // ── Convert workbook to Buffer ─────────────────────────────────────────
  // writeBuffer() returns a Promise<Buffer> — this Buffer is what we stream
  // to the browser or save to disk
  const buffer = await workbook.xlsx.writeBuffer();
  return buffer;
};

module.exports = { generateExcelReport };